/*
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * Copyright (C) 2012- The GROMACS Authors
 * Copyright (C) 2025 GaoZheng
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * ---
 *
 * This file is part of a modified version of the GROMACS molecular simulation package.
 * For details on the original project, consult https://www.gromacs.org.
 *
 * To help fund GROMACS development, we humbly ask that you cite
 * the research papers on the package. Check out https://www.gromacs.org.
 */

/*
 * Note: this file was generated by the Verlet kernel generator for
 * kernel type 2xmm.
 */

/* Some target architectures compile kernels for only some NBNxN
 * kernel flavours, but the code is generated before the target
 * architecture is known. So compilation is conditional upon
 * KernelLayout::r2xMM, so that this file reduces to a stub
 * function definition when the kernel will never be called.
 */
#include "gmxpre.h"

#include "gromacs/mdtypes/interaction_const.h"
#include "gromacs/nbnxm/nbnxm_simd.h"
#if GMX_HAVE_NBNXM_SIMD_2XMM
#    include "gromacs/nbnxm/simd_kernel.h"

namespace gmx
{

template void nbnxmKernelSimd<KernelLayout::r2xMM,
                              KernelCoulombType::EwaldTabulated,
                              VdwCutoffCheck::No,
                              LJCombinationRule::Geometric,
                              InteractionModifiers::PotShift,
                              LJEwald::None,
                              EnergyOutput::System>(const NbnxnPairlistCpu*    nbl,
                                                    const nbnxn_atomdata_t*    nbat,
                                                    const interaction_const_t* ic,
                                                    const rvec*                shift_vec,
                                                    nbnxn_atomdata_output_t*   out);

} // namespace gmx

#endif // GMX_HAVE_NBNXM_SIMD_2XMM
